### ISSUE TITLE
Compiling instructions for Windows missing a library link

### ISSUE THREAD

**Issue by ghost** [hadron13/Squareroot-mining#1]
The instructions to compile the game for Windows in the README file are missing a library flag: `-lmingw32`. It allows SDL to call the WinMain function, and without it, the game will probably not even compile.

**Comment by hadron13** [comment]
I'm using mingw w64 on Linux, it did work for me and the .exe worked with Windows users, i'll put that into the README, just for sure

**Comment by ghost** [comment]
> I'm using mingw w64 on Linux, it did work for me and the .exe worked with Windows users, i'll put that into the README, just for sure

That's for 64 bit x86 architecture. For 32 bit the library is needed. I suggest even putting this as a note in the README file. Gonna close the issue.

Keep it up
